version: 0.2

phases:
  install:
    commands:
      - echo "Starting deployment for subdomain - $SUB"
      - if [[ -z "$SUB" || -z "$DEPLOY_ENV" ]]; then echo "ERROR - SUB or DEPLOY_ENV environment variables not set"; exit 1; fi
      - echo "Environment - $DEPLOY_ENV"
      - echo "Subdomain - $SUB"
      - cd subs/$SUB

  pre_build:
    commands:
      - echo "Fetching deployment configuration from Parameter Store"
      - export TARGET_BUCKET=$(aws ssm get-parameter --name /spooky-decs/$SUB/$DEPLOY_ENV/s3-bucket --query 'Parameter.Value' --output text)
      - export DISTRIBUTION_ID=$(aws ssm get-parameter --name /spooky-decs/$SUB/$DEPLOY_ENV/cf-distribution --query 'Parameter.Value' --output text)
      - if [[ -z "$TARGET_BUCKET" || -z "$DISTRIBUTION_ID" ]]; then echo "ERROR - Failed to fetch parameters from SSM"; echo "TARGET_BUCKET - $TARGET_BUCKET"; echo "DISTRIBUTION_ID - $DISTRIBUTION_ID"; exit 1; fi
      - echo "Target S3 Bucket - $TARGET_BUCKET"
      - echo "CloudFront Distribution - $DISTRIBUTION_ID"

  build:
    commands:
      - echo "Deploying vanilla JS files for $SUB"
      - echo "Syncing files to S3 bucket - $TARGET_BUCKET"
      - aws s3 sync . s3://$TARGET_BUCKET --delete --exclude ".git/*" --exclude "*.md" --exclude ".gitignore"
      - echo "✅ S3 sync completed"
      - echo "Verifying critical files in S3"
      - aws s3 ls s3://$TARGET_BUCKET/ --recursive | grep "index.html" || echo "Warning - index.html not found"

  post_build:
    commands:
      - echo "Creating CloudFront invalidation"
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --no-cli-pager
      - echo "✅ Deployment complete for $SUB in $DEPLOY_ENV environment"
      - echo "Site URL - https://$SUB.spookydecs.com"