version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI dependencies"
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Deploying to environment $DEPLOY_ENV" #this variable is set in the CodeBuild console under advanced settings
      - if [[ -z "$DEPLOY_ENV" ]]; then
          echo "DEPLOY_ENV not set. Aborting deployment.";
          exit 1;
        fi
      - echo "Setting environment variables" 
      - echo $DEPLOY_ENV "is the environment, fool"
      - export ENV=$DEPLOY_ENV
      
      # Fetch pipeline configuration
      - echo "Fetching pipeline configuration from Parameter Store"
      - export TARGET_BUCKET=$(aws ssm get-parameter --name /spooky-decs/deployments/$ENV/s3-bucket --query 'Parameter.Value' --output text)
      - export DISTRIBUTION_ID=$(aws ssm get-parameter --name /spooky-decs/deployments/$ENV/cf-distribution --query 'Parameter.Value' --output text)
      - echo "Will deploy to $TARGET_BUCKET with CloudFront $DISTRIBUTION_ID"
      
      # Generate application config.json
      - echo "Generating config.json from Parameter Store"
      - chmod +x generate-config.sh
      - ./generate-config.sh $ENV

  build:
    commands:
      - echo "Syncing files to S3"
      - aws s3 sync . s3://$TARGET_BUCKET --delete --exclude ".git/*" --exclude "buildspec.yml" --exclude ".gitignore" --exclude "README.md" --exclude "test.txt" --exclude "generate-config.sh"
      - echo "S3 sync complete"

  post_build:
    commands:
      - echo "Creating CloudFront invalidation"
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo "Deployment complete"

artifacts:
  files:
    - '**/*'